(function(c,e,h,k){var f=c(e);c.fn.lazyload=function(a){function b(){var a=0;g.each(function(){var b=c(this);if(!(d.skip_invisible&&!b.is(":visible")||c.abovethetop(this,d)||c.leftofbegin(this,d)))if(!c.belowthefold(this,d)&&!c.rightoffold(this,d))b.trigger("appear"),a=0;else if(++a>d.failure_limit)return!1})}var g=this,d={threshold:0,failure_limit:0,event:"scroll",effect:"show",container:e,data_attribute:"original",skip_invisible:!1,appear:null,load:null,placeholder:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"};
a&&(void 0!==a.failurelimit&&(a.failure_limit=a.failurelimit,delete a.failurelimit),void 0!==a.effectspeed&&(a.effect_speed=a.effectspeed,delete a.effectspeed),c.extend(d,a));a=void 0===d.container||d.container===e?f:c(d.container);0===d.event.indexOf("scroll")&&a.bind(d.event,function(){return b()});this.each(function(){var a=this,b=c(a);a.loaded=!1;(void 0===b.attr("src")||!1===b.attr("src"))&&b.is("img")&&b.attr("src",d.placeholder);b.one("appear",function(){this.loaded||(d.appear&&d.appear.call(a,
g.length,d),c("\x3cimg /\x3e").bind("load",function(){var e=b.attr("data-"+d.data_attribute);b.hide();b.is("img")?b.attr("src",e):b.css("background-image","url('"+e+"')");b[d.effect](d.effect_speed);a.loaded=!0;e=c.grep(g,function(a){return!a.loaded});g=c(e);d.load&&d.load.call(a,g.length,d)}).attr("src",b.attr("data-"+d.data_attribute)))});0!==d.event.indexOf("scroll")&&b.bind(d.event,function(){a.loaded||b.trigger("appear")})});f.bind("resize",function(){b()});/(?:iphone|ipod|ipad).*os 5/gi.test(navigator.appVersion)&&
f.bind("pageshow",function(a){a.originalEvent&&a.originalEvent.persisted&&g.each(function(){c(this).trigger("appear")})});c(h).ready(function(){b()});return this};c.belowthefold=function(a,b){return(void 0===b.container||b.container===e?(e.innerHeight?e.innerHeight:f.height())+f.scrollTop():c(b.container).offset().top+c(b.container).height())<=c(a).offset().top-b.threshold};c.rightoffold=function(a,b){return(void 0===b.container||b.container===e?f.width()+f.scrollLeft():c(b.container).offset().left+
c(b.container).width())<=c(a).offset().left-b.threshold};c.abovethetop=function(a,b){return(void 0===b.container||b.container===e?f.scrollTop():c(b.container).offset().top)>=c(a).offset().top+b.threshold+c(a).height()};c.leftofbegin=function(a,b){return(void 0===b.container||b.container===e?f.scrollLeft():c(b.container).offset().left)>=c(a).offset().left+b.threshold+c(a).width()};c.inviewport=function(a,b){return!c.rightoffold(a,b)&&!c.leftofbegin(a,b)&&!c.belowthefold(a,b)&&!c.abovethetop(a,b)};
c.extend(c.expr[":"],{"below-the-fold":function(a){return c.belowthefold(a,{threshold:0})},"above-the-top":function(a){return!c.belowthefold(a,{threshold:0})},"right-of-screen":function(a){return c.rightoffold(a,{threshold:0})},"left-of-screen":function(a){return!c.rightoffold(a,{threshold:0})},"in-viewport":function(a){return c.inviewport(a,{threshold:0})},"above-the-fold":function(a){return!c.belowthefold(a,{threshold:0})},"right-of-fold":function(a){return c.rightoffold(a,{threshold:0})},"left-of-fold":function(a){return!c.rightoffold(a,
{threshold:0})}})})(jQuery,window,document);
$(function(){$("img.lazy").show().lazyload({effect:"fadeIn",event:"sporty"})});$(window).bind("load",function(){setTimeout(function(){$("img.lazy").trigger("sporty")},600)});
$(function(){var a=$(".product-name");$.each(a,function(b,c){30<$(a[b]).text().length&&$(a[b]).text($(this).text().substring(0,30)+"...")})});
