urlPath=$("#urlPath").val();
function ShoppingCart(a,c){return{subTotal:a,setTotal:function(b){return 0<b?a+b:a}}};
function ShoppingItem(a,b){return{quantity:a,price:b}};
function ShoppingItemUI(a){var b=a.find(".cart_quantity_input"),c=a.find(".cart_total_price_value");return{update:function(a){b.val(a.quantity);c.text(a.price)}}};
function ShoppingCartUI(){var b=$(".total_area").find(".price-subtotal"),c=$(".total_area").find(".price-total"),d=$(".price-freight"),e={_setSubTotal:function(a){b.text(a);this._evaluateFreight()},getTotal:function(){return c},_setTotal:function(a){c.text(a)},setFreight:function(a){d.text(a);this._evaluateFreight()},getFreight:function(){return parseFloat(d.text())},_createShoppingCart:function(){return new ShoppingCart(parseFloat(b.text()))},_evaluateFreight:function(){var a=this._createShoppingCart().setTotal(this.getFreight());
this._setTotal(a.toFixed(1))},update:function(a){this._setSubTotal(a.subTotal)}};window.onload=e._evaluateFreight();return e};
function FreightMessageUI(a){var b=a.find(".deadline"),c=a.find(".msgError");return{update:function(a){b.text(a.deadline);c.text(a.msgError)}}};
function HttpService(){var b=$("#urlPath").val();return{post:function(a){return $.ajax({method:"POST",url:b+a.path,data:a})}}};
function ShoppingCartService(){var b=new HttpService;return{increaseItem:function(a){a.path="v1/shopping/increaseItem";return b.post(a)},decreaseItem:function(a){a.path="v1/shopping/decreaseItem";return b.post(a)},changeItemQuantity:function(a){a.path="v1/shopping/changeItemQuantity";return b.post(a)}}};
function CorreiosService(c){var b=new HttpService;return{calculate:function(a){a.path="v1/correios/calculate";return b.post(a)}}};
$(function(){var f=new ShoppingCartUI,d=new ShoppingCartService,k=new CorreiosService,e=function(a){a.preventDefault();var b=$(this),c=b.closest(".cart_body"),g=c.find(".loading"),d=new ShoppingItemUI(c),b={productId:c.find(".item_id").val(),quantity:b.val()||""};g.show();$.when(a.data.callback(b)).then(function(a,b,c){b=new ShoppingCart(a.priceSubTotal);f.update(b);a=new ShoppingItem(a.quantity,a.priceItem);d.update(a)}).always(function(){g.hide()})},h=function(a){a.preventDefault();if(0==$(this).val().length){a=
$(this).closest(".cep-area");var b=new FreightMessageUI(a),c=a.find(".loading");a={cep:a.find(".cep-input").val()};c.show();$.when(k.calculate(a)).then(function(a,c,d){b.update(a);f.setFreight(a.freight)}).always(function(){c.hide()})}};$(".cart_quantity_up").click({callback:function(a){return d.increaseItem(a)}},e);$(".cart_quantity_down").click({callback:function(a){return d.decreaseItem(a)}},e);$(".cart_quantity_input").on("change blur",{callback:function(a){return d.changeItemQuantity(a)}},e);
$(".cep-calculation").click(h);$(".cep-input").blur(h)});
