
serverContext='http://localhost:8080/e-shopper/';

var changeCartQuantityAjax=function(dataTarget){var productId=dataTarget.item.find('.item_id').val();var quantity=dataTarget.quantity;var quantityItem=dataTarget.item.find('.cart_quantity_input');var priceItem=dataTarget.item.find('.cart_total_price_value');var loadingState=dataTarget.item.find('.loading');$.ajax({method:'GET',url:dataTarget.url,data:{productId:productId,quantity:quantity},beforeSend:function(){loadingState.show();},success:function(data){loadingState.hide();quantityItem.val(data.quantity);priceItem.text(data.priceItem);$shoppingCart.text(data.quantityTotal);$subTotal.text(data.priceSubTotal);$total.text(data.priceTotal+window.freight);}});}
var correiosCalculationAjax=function(row){var cep=row.find('.cep-input').val();var freight=row.find('.price-freight');var priceSubTotal=row.find('.price-subtotal');var priceTotal=row.find('.price-total');var deadline=row.find('.deadline');var loadingState=row.find('.loading');$.ajax({method:'GET',url:serverContext+'v1/correios/calculate',data:{cep:cep},beforeSend:function(){loadingState.show();},success:function(data){loadingState.hide();freight.text(data.freight);priceTotal.text(parseFloat(priceSubTotal.text())+parseFloat(freight.text()));deadline.text(data.deadline);row.find('.msgError').text(data.msgError);}});};

$(function(){$shoppingCart=$('body').find('.shopping-cart');$subTotal=$('body').find('.price-subtotal');$total=$('body').find('.price-total');window.freight=0;var changeCartQuantityButton=function(event){event.preventDefault();var data={item:$(this).closest('.cart_body'),url:event.data.url};changeCartQuantityAjax(data);}
var changeCartQuantityInput=function(event){event.preventDefault();var data={item:$(this).closest('.cart_body'),quantity:$(this).val(),url:event.data.url};changeCartQuantityAjax(data);}
var correriosCalculation=function(event){event.preventDefault();var row=$(this).closest('.row');correiosCalculationAjax(row);}
var checkEmptyInputCep=function(){if($(this).val().length==0){var row=$(this).closest('.row');correiosCalculationAjax(row);}}
$('.cart_quantity_up').click({url:serverContext+'v1/shopping/increaseItem'},changeCartQuantityButton);$('.cart_quantity_down').click({url:serverContext+'v1/shopping/decreaseItem'},changeCartQuantityButton);$('.cart_quantity_input').on('change blur',{url:serverContext+'v1/shopping/changeItemQuantity'},changeCartQuantityInput);$('.cep-calculation').click(correriosCalculation);$('.cep-input').blur(checkEmptyInputCep);});
