urlPath=$("#urlPath").val();
function ShoppingCart(a,c){return{subTotal:a,setTotal:function(b){return 0<b?a+b:a}}};
function ShoppingItem(a,b){return{quantity:a,price:b}};
function ShoppingItemUI(a){var b=a.find(".cart_quantity_input"),c=a.find(".cart_total_price_value");return{update:function(a){b.val(a.quantity);c.text(a.price)}}};
function ShoppingCartUI(){var b=$(".total_area").find(".price-subtotal"),c=$(".total_area").find(".price-total"),d={_setSubTotal:function(a){b.text(a);this._evaluateFreight()},getTotal:function(){return c},_setTotal:function(a){c.text(a)},getFreight:function(){return parseFloat($(".price-freight").text())},_createShoppingCart:function(){return new ShoppingCart(parseFloat(b.text()))},_evaluateFreight:function(){var a=this._createShoppingCart().setTotal(this.getFreight());this._setTotal(a.toFixed(2))},
update:function(a){this._setSubTotal(a.subTotal)}};window.onload=d._evaluateFreight();return d};
function ShoppingCartService(){var b=new HttpService;return{post:function(a){a.resource="v1/shopping/increaseItem";return b.post(a).always(function(b){a.loadingState.hide()})}}};
var correiosCalculationAjax=function(a){var f=a.find(".cep-input").val(),e=a.find(".loading");$.ajax({method:"GET",url:urlPath+"v1/correios/calculate",data:{cep:f},beforeSend:function(){e.show()},success:function(a){e.hide()}}).done(function(b){var c=a.find(".price-freight");c.text(b.freight);a.find(".deadline").text(b.deadline);a.find(".msgError").text(b.msgError);var d=a.find(".price-subtotal");b=a.find(".price-total");d=parseFloat(d.text());c=parseFloat(c.text());b.text(d+c).toFixed(2)})};
$(function(){shoppingCartUI=new ShoppingCartUI;shoppingCartService=new ShoppingCartService;var b=function(a){a.preventDefault();a=$(this);var b=a.closest(".cart_body"),c=new ShoppingItemUI(b);a={productId:b.find(".item_id").val(),quantity:a.val()||"",loadingState:b.find(".loading")};$.when(shoppingCartService.post(a)).then(function(a,b,d){b=new ShoppingCart(a.priceSubTotal);shoppingCartUI.update(b);a=new ShoppingItem(a.quantity,a.priceItem);c.update(a)})},c=function(a){a.preventDefault();0==$(this).val().length&&
(a=$(this).closest(".cep-area"),correiosCalculationAjax(a))};$(".cart_quantity_up").click({resource:"v1/shopping/increaseItem"},b);$(".cart_quantity_down").click({resource:"v1/shopping/decreaseItem"},b);$(".cart_quantity_input").on("change blur",{resource:"v1/shopping/changeItemQuantity"},b);$(".cep-calculation").click(c);$(".cep-input").blur(c)});
